server:
  port: 8090

dubbo:
  protocol:
    name: dubbo
    port: 12345
  application:
    name: pers.ocean.demo_provider
  scan:
    base-packages: pers.ocean.service
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 20000
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  config-center:
    timeout: 30000