spring:
  application:
    name: dubbo-demo-consumer
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181